### ISSUE TITLE
How to override inline CSS?

### ISSUE THREAD

**Issue by pssuralkar** [TeamWertarbyte/material-auto-rotating-carousel#10]
Hi, Could you please help me on below issue.
I am facing issue in inline CSS style which is added dynamically below is the code for reference: 
```
(
width:60%; 
max-width:700px; 
height:calc(100% - 96px); 
max-height:600px; 
margin:-16px auto 0;
position:relative;
top:50%; 
transform:translateY(-50%);
)
```
Thanks in Advance.

**Comment by leMaik** [comment]
Could you please tell me which issue you face?

**Comment by saschb2b** [comment]
What exactly are you trying to produce at the end? Seems like you want to embed it in a container precisely? If so see please #6
This component is not intendet for embedding pruposes. It's like google designed it. Always on top before anything will happen. It's to introduce your users to your app. Not an extra sliding component. If you are just searching for a sliding way see the swipeable view dependency component, which does exactly that.

**Comment by pssuralkar** [comment]
Thanks for your replay.
I wanted to add custom width for container section through css. 
Current width is 60% and added dynamically. 
Now I wanted to make it 100% width for container section. 
Can you please assist how to add or override custom css?

**Comment by saschb2b** [comment]
I added a contentStyle prop and the style prop to the readme in version 1.3.0 . Setting width and maxWidth to 100% over contentStyle will stretch it out. I just want to point out that it's not intendet to be out of bounce. we stayed strictly after the google design guidelines.

**Comment by pssuralkar** [comment]
Thanks for your replay, I can see you have added fixed width i.e 60% for outer content, which I wanted to override with 100%. if you can inspect below code then you can see below inline css for below code.

CSS Code which is apply dynamically  
(
width:60%; 
max-width:700px; 
height:calc(100% - 96px); 
max-height:600px; 
margin:-16px auto 0;
position:relative;
top:50%; 
transform:translateY(-50%);
)

Below is the Auto Rotating Carousel Code.

<div className={'slider'}>
                <AutoRotatingCarousel style={{ position: 'inherit', width:'100%', backgroundColor:'transparent', boxShadow:'none'}}
                                      label='Vanqor Limited'
                                      open={true}
                                      landscape={true}
                                      mobile={false}
                                      interval={100000000000}
                                      >
                  <Slide
                    media={<img src='../../static/Common/Apple-Devices.png' className={'bannerImg'}/>}
                    mediaBackgroundStyle={{ backgroundColor:'transparent', display:'inline-block', float:'right'}}
                    contentStyle={{backgroundColor:'transparent', textAlign:'left', color:'white', maxWidth:'100%'}}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                   />

                  <Slide
                    media={<img src='http://www.icons101.com/icon_png/size_256/id_80975/GoogleInbox.png' />}
                    mediaBackgroundStyle={{ backgroundColor:transparent, display:'inline-block', float:'right'}}
                    contentStyle={{ backgroundColor: transparent, }}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                    />

                  <Slide
                    media={<img src='http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png' />}
                    mediaBackgroundStyle={{ backgroundColor:transparent, display:'inline-block', float:'right'}}
                    contentStyle={{ backgroundColor: transparent }}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                    />

                </AutoRotatingCarousel>

                </div>  

Thanks in advance.

**Comment by saschb2b** [comment]
Use the contentStyle of AutoRotatingCarousel no from every slide.

```
<div className={'slider'}>
                <AutoRotatingCarousel style={{ position: 'inherit', width:'100%', backgroundColor:'transparent', boxShadow:'none'}}
                                      label='Vanqor Limited'
                                      open={true}
                                      landscape={true}
                                      mobile={false}
                                      interval={100000000000}
                                     contentStyle={{
width:60%; 
max-width:700px; 
height:calc(100% - 96px); 
max-height:600px; 
margin:-16px auto 0;
position:relative;
top:50%; 
transform:translateY(-50%);
}}
                                      >
                  <Slide
                    media={<img src='../../static/Common/Apple-Devices.png' className={'bannerImg'}/>}
                    mediaBackgroundStyle={{ backgroundColor:'transparent', display:'inline-block', float:'right'}}
                    contentStyle={{backgroundColor:'transparent', textAlign:'left', color:'white', maxWidth:'100%'}}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                   />

                  <Slide
                    media={<img src='http://www.icons101.com/icon_png/size_256/id_80975/GoogleInbox.png' />}
                    mediaBackgroundStyle={{ backgroundColor:transparent, display:'inline-block', float:'right'}}
                    contentStyle={{ backgroundColor: transparent, }}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                    />

                  <Slide
                    media={<img src='http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png' />}
                    mediaBackgroundStyle={{ backgroundColor:transparent, display:'inline-block', float:'right'}}
                    contentStyle={{ backgroundColor: transparent }}
                    title="This is a very cool feature"
                    subtitle="Just using this will blow your mind."
                    />
                </AutoRotatingCarousel>
                </div>  
```

**Comment by pssuralkar** [comment]
Hi, If possible can you please share your email id so I can send you screenshot with inspected code so you will get more idea on that issue.

**Comment by saschb2b** [comment]
You can add screenshots here. Share it with the community. That's the point of open source projects

**Comment by pssuralkar** [comment]
<img width="1920" alt="screengrab1" src="https://cloud.githubusercontent.com/assets/20420448/23017222/52bb395a-f431-11e6-8b90-4cf95b688ad2.png">

I have added screenshot with inspected code which i want to override with

**Comment by saschb2b** [comment]
That the style defined in `style.content` which can be overriden by using the prop contentStyle of the AutRotatingCarousel as published with version 1.3 since yesterday.

**Comment by pssuralkar** [comment]
as per your solution that style applied exact above of the selected code in inspect tool but I wanted to override highlighted code only.

**Comment by saschb2b** [comment]
Maybe we have a communication issue but using

```
<AutoRotatingCarousel style={{ position: 'inherit', width:'100%', backgroundColor:'transparent', boxShadow:'none'}}
                                      label='Vanqor Limited'
                                      open={true}
                                      landscape={true}
                                      mobile={false}
                                      interval={100000000000}
                                     contentStyle={{
your custom content css HERE!!!!111!!
}}

Will allow you to change exactly this container style. But I want to point out once more that your use case is really not what this component was intended for. Please see the linked google document in the readme what this component should be used for. You may be better of implementing your own buttons and dots (just see our code as inspiration) and use swipeable views component to build your use case.

**Comment by pssuralkar** [comment]
Thanks. just one question if I want to remove box-shadow and border radius which is applied in outer content. So should I need to add custom style in contentStyle={{ }} section. Is that right?

**Comment by leMaik** [comment]
@pssuralkar You would be better if you'd just use a different slide component for your use-case instead of abusing this component to fit your needs.
Everytime a developer styles this component to look/behave differently than the Material Specs intended, a designer kills a unicorn. Please help saving the unicorns! :unicorn:

**Comment by pssuralkar** [comment]
thanks

**Comment by pipzpadilla** [comment]
how to hide the dots and arrows???

**Comment by saschb2b** [comment]
@pipzpadilla This component is designed with google material design in mind. If you hide the arrows and dots there is nearly no action at all it's not aligned with the design specs anymore.  You can however use the `mobile` prop to force the mobile view without the arrows left and right.
The dots are still there. 

For now I would recomment using the underlying module https://github.com/oliviertassinari/react-swipeable-views if you need just some raw slides.

**Comment by daumann** [comment]
@leMaik @saschb2b it is good practice to expose all containers used via API for styling. Especially if it is a visual component like this. Unreachable containers are very frustrating...

Also, a carousel with different dots and arrows/ 0 border radius can very well be material design. Just have a look at the [Google Earth Carousel](https://earth.google.com/web/) (click on Voyager icon left).

Despite that, thank you for your MIT licenced component, it is unfortunately the best material design/ react carousel available so far.

**Comment by leMaik** [comment]
> it is unfortunately the best material design/ react carousel available so far.

@daumann Could you elaborate on why this is unfortunate?

**Comment by daumann** [comment]
@leMaik I understand and thanks for this great component. The only thing I don't understand is that you are against the idea of exposing containers for _optional_ customized styling by devs. This won't take away from your project and would not require a lot of effort on your side.

**Comment by leMaik** [comment]
@daumann Okay, I could expose the inline styles. But that still wouldn't give developers the ultimate flexibility they might want. But I don't want to expose renderers for the dots, the arrows, etc. That's what would bring a lot of additional complexity into the code.

**Comment by leMaik** [comment]
@daumann Since there were so many requests, the inline styles are finally going to be exposed. :+1: See #23
