### ISSUE TITLE
Support for material-ui@^0.18

### ISSUE THREAD

**Issue by mjsevilla** [TeamWertarbyte/material-auto-rotating-carousel#14]
`npm WARN material-auto-rotating-carousel@1.3.1 requires a peer of material-ui@^0.17.4 but none was installed.`

Can I still use this if I'm running material-ui 0.18?

**Comment by leMaik** [comment]
I started to set the peer dependency of material-ui to `< 1.0.0`, treating anything that doesn't work with a version below that as a bug.
So yes, it should work fine. :+1:
