### ISSUE TITLE
Open slides by clicking the small dots

### ISSUE THREAD

**Issue by mjsevilla** [TeamWertarbyte/material-auto-rotating-carousel#15]
Is there a way to add back the clickable arrow keys when the `mobile` prop is set to true? I want the edge-to-edge carousel but also want users to click between slides, not just use their arrow keys.

**Comment by leMaik** [comment]
No, that's not possible as we stick to the Material Design specs and there are no arrow buttons in the "edge to edge" mode.
What we could do is make the small dots clickable in order to navigate directly to a page. How about that?

**Comment by mjsevilla** [comment]
Yeah, that sounds great! I'm implementing a few more than three slides, so it would be a nice to have feature for users to click to further slides if they would prefer over swiping continuously. With that said, this next question may sound silly, but if I were to put this on a giant touch screen, a user would be able to swipe between each slide, yes?

**Comment by leMaik** [comment]
Yes, thanks to react-swipeable-views, the user can swipe just fine. :+1:

**Comment by leMaik** [comment]
I just published v1.4.0 which adds support for clicking on the small dots to navigate through the slides. :tada:
