### ISSUE TITLE
Exposing Dots as a standalone component

### ISSUE THREAD

**Issue by TeaSeaLancs** [TeamWertarbyte/material-auto-rotating-carousel#16]
Hi there,

Would it be possible to expose the `Dots` component as its own component, potentially with its own repo?

There are circumstances where i'm developing a carousel which doesn't fit into the Top User Benefits design which this component adheres to, so using this component outright isn't possible.

I'm creating my own view using `react-swipeable-views` as you have, and it would be fantastic to reuse the `Dots` component you have as it looks excellent!

**Comment by leMaik** [comment]
I was thinking about making the dots their own independent project but then I thought that, well, they are just dots. :smile: But now that the dots are animated, the dots might be of use for more projects. :thinking:

I'll release them asap, looking to see what you'l make out of them! :+1:

**Comment by TeaSeaLancs** [comment]
That's great, thanks so much :) And yeah, the animation is great, really nice work on that.

**Comment by leMaik** [comment]
Thank you! :blush:

**Comment by leMaik** [comment]
[Done!](https://github.com/TeamWertarbyte/material-ui-dots)

**Comment by TeaSeaLancs** [comment]
![Thanks!](https://media.giphy.com/media/qPVzemjFi150Q/giphy.gif)
