### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by leMaik** [TeamWertarbyte/material-auto-rotating-carousel#2]
This feature would almost be free and pretty useful for users that expect to have keyboard navigation, especially on the desktop.

**Comment by oliviertassinari** [comment]
You could be using the `bindKeyboard` HOC of *react-swipeable-views*.

**Comment by leMaik** [comment]
@oliviertassinari Wow, that was easy. :+1: 
Any idea how I could get the spring to be more material-like (using the same bezier curve that the dots use)?

**Comment by oliviertassinari** [comment]
Well, that's a good question. You need to tweak the `springConfig` property.
React-motion has a demo where you can play with different value. You would need to find the one that feels right. I know that there is section on the Material Specification regarding the expected transformation function curve. It's physical based. That shouldn't be too hard. As react-motion is also using a spring physical model with some friction.

**Comment by leMaik** [comment]
Okay, I'll tweak the spring config then. Combining three HOCs [is strange](oliviertassinari/react-swipeable-views/issues/156), by the way, but it works now.
