### ISSUE TITLE
Can we modify the left/right button?

### ISSUE THREAD

**Issue by mirocody** [TeamWertarbyte/material-auto-rotating-carousel#22]
Thank you for your awesome work! But I want to modify the styles of the button, or even remove the button. Could you please make them as optional, or let dev could modify their style?

**Comment by leMaik** [comment]
Please take a look at #10 to see why we don't support that at the moment.

If you remove the buttons, wouldn't you just end up with a slide show? :thinking:

**Comment by mirocody** [comment]
Hi @leMaik thank you for the response. I checked your comment there and I was wondering if the inline styles are exposed to the devs now? In my case the space between container and arrow is too wide so I need either modify the style or just delete. 
As my personal preference, I would like to delete the arrorw but just keep the dots.

**Comment by leMaik** [comment]
I'd be okay with adding a prop to hide the buttons in the desktop version. :+1: Want to create a PR?

**Comment by mirocody** [comment]
Sure I can do that. Do you just want a prop to make the button optional, or also expose the inline style to the devs?

**Comment by leMaik** [comment]
Well... I don't _want_ to, but there are so many requests that I think we should finally add that. :confused: But please split the PRs. :wink:

**Comment by mirocody** [comment]
Hi I am new to npm, I forked this repo and made change to my forked repo, then replace 
"material-auto-rotating-carousel": 'version' with my forked github address `"https://github.com/mirocody/material-auto-rotating-carousel/tarball/master",` to test that. But after doing the `npm install` it shows cannot find module `material-auto-rotating-carousel`, do you have any idea how to solve it?

**Comment by leMaik** [comment]
No need to modify anything in the `package.json`. Just fork it, run `npm install` and start coding. :wink:

**Comment by mirocody** [comment]
Thanks. I just created PR for hide button and would create a separate PR for exposing the inline style later.
My question for npm is: I try to import my forked(with modification) material-auto-rotating-carousel  to my another project(`project A`). And in package.json from that project, I have this line `"material-auto-rotating-carousel": "github:mirocody/material-auto-rotating-carousel"`, however after npm install it still shows module not found;
Then I go to local forked material-auto-rotating-carousel folder and do the npm build, and copy the `lib` folder to the node modules under project A, then everything works. 
And I wander if there is a way that I just do npm install and then it would install my forked library with the `lib` folder? Any idea is appreciated I am totally new to npm, and did not find other solution for this issue

**Comment by mirocody** [comment]
Hmmm and one more question, I tested by `npm run storybook` and could get the demo, but the code changed in `AnimationDemo.js` does not apply to the web. 🤔

**Comment by leMaik** [comment]
Go in project A's directory and run `npm link <path to your material-auto-rotating-carousel directory>`. Voilà, linked! :sunglasses: 

Remember that you need to build the project in order to use it linked, run `npm run build` in the material-auto-… directory.

**Comment by leMaik** [comment]
@mirocody I'm reopening this since your PR adresses this issue :+1:
