### ISSUE TITLE
Issue with material-ui paths

### ISSUE THREAD

**Issue by barbush** [TeamWertarbyte/material-auto-rotating-carousel#30]
Hi,

The material paths changed I think e.g. colors are in material-ui/colors excluding /styles

Installing I got the following errors:

These dependencies were not found:

* material-ui/RaisedButton in ./~/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js
* material-ui/styles/colors in ./~/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js, ./~/material-auto-rotating-carousel/lib/Slide.js
* material-ui/svg-icons/navigation/arrow-back in ./~/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js
* material-ui/svg-icons/navigation/arrow-forward in ./~/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js

To install them, you can run: npm install --save material-ui/RaisedButton material-ui/styles/colors material-ui/svg-icons/navigation/arrow-back material-ui/svg-icons/navigation/arrow-forward

**Comment by leMaik** [comment]
This component is not yet compatible with material-ui@1.0.0-beta. We will port it soon. :)

**Comment by leMaik** [comment]
I'll close this as duplicate of #25.
