### ISSUE TITLE
Raised Button is not in material-ui's library

### ISSUE THREAD

**Issue by SuperBerny** [TeamWertarbyte/material-auto-rotating-carousel#31]
Can't resolve 'material-ui/RaisedButton' from node_modules\material-auto-rotating-carousel\lib' 

I tried importing { Button } from 'material-ui' on AutoRotatingCarousel.js instead of { RaisedButton } but still get the same error that it can't resolve material-ui/RaisedButton.

**Comment by Koerner** [comment]
Try this:
`import FlatButton from 'material-ui/FlatButton';` or `import RaisedButton from 'material-ui/RaisedButton';`

**Comment by SuperBerny** [comment]
Get this error: 
./node_modules/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js
Module not found: Can't resolve 'material-ui/RaisedButton' in 'C:\Users\brian\Desktop\Bootcamp\Kuche\client\node_modules\material-auto-rotating-carousel\lib'

With this code:
```
import React, { Component } from 'react';
// import FlatButton from 'material-ui/FlatButton'
import RaisedButton from 'material-ui/RaisedButton';
import { AutoRotatingCarousel, Slide } from 'material-auto-rotating-carousel'
import { green400, green600, blue400, blue600, red400, red600 } from 'material-ui/styles/colors'

class Carousel extends Component {

  render() {
    return (
      <div>
        <AutoRotatingCarousel
          label="Get started"
          open
        >
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_79394/youtube.png" />}
            mediaBackgroundStyle={{ backgroundColor: red400 }}
            contentStyle={{ backgroundColor: red600 }}
            title="This is a very cool feature"
            subtitle="Just using this will blow your mind."
          />
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_80975/GoogleInbox.png" />}
            mediaBackgroundStyle={{ backgroundColor: blue400 }}
            contentStyle={{ backgroundColor: blue600 }}
            title="Ever wanted to be popular?"
            subtitle="Well just mix two colors and your are good to go!"
          />
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png" />}
            mediaBackgroundStyle={{ backgroundColor: green400 }}
            contentStyle={{ backgroundColor: green600 }}
            title="May the force be with you"
            subtitle="The Force is a metaphysical and ubiquitous power in the Star Wars universe."
          />
        </AutoRotatingCarousel>
      </div>
    )
  }
}

export default Carousel;)
```

With this code: 

`import React, { Component } from 'react';
import FlatButton from 'material-ui/FlatButton'
// import RaisedButton from 'material-ui/RaisedButton';
import { AutoRotatingCarousel, Slide } from 'material-auto-rotating-carousel'
import { green400, green600, blue400, blue600, red400, red600 } from 'material-ui/styles/colors'

class Carousel extends Component {

  render() {
    return (
      <div>
        <AutoRotatingCarousel
          label="Get started"
          open
        >
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_79394/youtube.png" />}
            mediaBackgroundStyle={{ backgroundColor: red400 }}
            contentStyle={{ backgroundColor: red600 }}
            title="This is a very cool feature"
            subtitle="Just using this will blow your mind."
          />
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_80975/GoogleInbox.png" />}
            mediaBackgroundStyle={{ backgroundColor: blue400 }}
            contentStyle={{ backgroundColor: blue600 }}
            title="Ever wanted to be popular?"
            subtitle="Well just mix two colors and your are good to go!"
          />
          <Slide
            media={<img src="http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png" />}
            mediaBackgroundStyle={{ backgroundColor: green400 }}
            contentStyle={{ backgroundColor: green600 }}
            title="May the force be with you"
            subtitle="The Force is a metaphysical and ubiquitous power in the Star Wars universe."
          />
        </AutoRotatingCarousel>
      </div>
    )
  }
}

export default Carousel;`

I get this error: 
./src/pages/GridList.js
Module not found: Can't resolve 'material-ui/FlatButton' in 'C:\Users\brian\Desktop\Bootcamp\Kuche\client\src\pages'

**Comment by leMaik** [comment]
You are most likely trying to use this component with material-ui@1.0.0, which is not yet possible. See #25 and #28 for progress in this. We'll port it soon :tm:
