### ISSUE TITLE
Allow customizing the style of the button

### ISSUE THREAD

**Issue by repl-ullas-ml** [TeamWertarbyte/material-auto-rotating-carousel#32]
Need ability to theme the button via setting style. 
http://www.material-ui.com/#/components/raised-button

**Comment by leMaik** [comment]
It's just not implemented at the moment. Feel free to submit a PR. :+1:

**Comment by leMaik** [comment]
This is now possible in v2.0.0 for Material-UI 1.0 using the `classes` prop.
