### ISSUE TITLE
Swipe left and right is not updating dotes view

### ISSUE THREAD

**Issue by repl-krishna-g** [TeamWertarbyte/material-auto-rotating-carousel#33]
Swipe left and right on mobile not updating dots and not notifying onChange(position)

**Comment by leMaik** [comment]
I'm afraid I can't reproduce this. https://next.mui.wertarbyte.com/#material-auto-rotating-carousel works fine when I swipe.

**Comment by xech3l0nx** [comment]
same thing happening here, had to disable pointer events to prevent users from swiping, and implement custom next button on mobile

**Comment by leMaik** [comment]
@repl-krishna-g @xech3l0nx I'll look into this issue. Could you please provide some more information, e.g. the browser where swiping doesn't work, the material-ui version you use, and any other information that is more specific than "here"? :wink:

**Comment by xech3l0nx** [comment]
as soon as I get it working and I can ship it into production I will share more info with you!
Now I am working on that other issue of the dialog not fitting into view on Safari Mobile because of the bottom navigation bar. ;-) 

Thanks for this library btw, it's saving me some time. 
The safari mobile one is a known issue

**Comment by leMaik** [comment]
@xech3l0nx So swiping doesn't work on _Safari_? :thinking:

**Comment by xech3l0nx** [comment]
it didn't work on Chrome as well, and not only on mobile, also in the chrome simulation of a mobile device viewport on desktop

**Comment by leMaik** [comment]
@xech3l0nx Regarding the viewport issues, here's a known ugly work around: https://github.com/TeamWertarbyte/material-auto-rotating-carousel/issues/20#issuecomment-355855158

**Comment by leMaik** [comment]
@xech3l0nx Could you please try to add `ignoreNativeScroll={true}` to the `AutoRotatingCarousel.js` file in your `node_modules/material-auto-rotating-carousel/lib` directory and see if this fixes the swiping issue?

**Comment by xech3l0nx** [comment]
Tried and it doesn't

These are the project's dependencies:

"material-auto-rotating-carousel": "^1.7.0",
"material-ui": "^0.16.7",
"react": "^15.6.2",

**Comment by leMaik** [comment]
@xech3l0nx Meh… Could you provide the code that embeds the carousel?

**Comment by xech3l0nx** [comment]
what do you mean? this?
```
<AutoRotatingCarousel
          autoplay={false}
          mobile={this.props.mobile}
          landscape={this.props.landscape}
          open={this.props.open}
          ref={instance => { this.child = instance; }}
        >
          <Slide
            className="slide"
            media={<img className="titleImg" src={`${cdn}/icons/Karma.svg`} />}
            mediaBackgroundStyle={{ backgroundColor: blue400 }}
            contentStyle={{ backgroundColor: blue600 }}
            title="LOREM IPSUM"            
            subtitle="LOREM IPSUM"
          />
{# other slides #}
</AutoRotatingCarousel>
```

**Comment by leMaik** [comment]
@xech3l0nx Hm… Looks fine so far. What components are _around_ the carousel? I can't reproduce this, so I guess there's something on the page that modifies the swiping behavior. :thinking: Could you please try putting the carousel on the root of your page and see if it works then?

**Comment by leMaik** [comment]
I'm closing this after over a month without a response. Feel free to re-open this issue if you need further help.

**Comment by leMaik** [comment]
Finally fixed this. The carousel didn't work with `autoplay={false}`. :open_mouth: #48
