### ISSUE TITLE
Incorrect number of slide count being rendered

### ISSUE THREAD

**Issue by repl-ullas-ml** [TeamWertarbyte/material-auto-rotating-carousel#34]
I have configured for 3 slides. But the the number of slides gets doubled ie to 6. Is there a prop property by which i can disable this?

**Comment by leMaik** [comment]
This shouldn't happen and I can't reproduce this. Could you please post the code you're using?

**Comment by leMaik** [comment]
I'll close this after almost two months without a response. Please re-open this with an example on how to reproduce the issue.
