### ISSUE TITLE
ContainerStyle is hardcoded

### ISSUE THREAD

**Issue by fadeenk** [TeamWertarbyte/material-auto-rotating-carousel#38]
This forces the carousel to take over the entire window. It will be nice to be able to overwrite this style. I am not sure if there is a way to do so and I am just blanking out on it.

https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/5640e0068c252eabe9f9ac08535b510a252226b1/src/AutoRotatingCarousel.js#L160

**Comment by leMaik** [comment]
Indeed. PR welcome. :+1:
