### ISSUE TITLE
is there an after change handler?

### ISSUE THREAD

**Issue by bartvde** [TeamWertarbyte/material-auto-rotating-carousel#4]
that gets called when the the index of carousel changes?

**Comment by saschb2b** [comment]
Currently not. Could you provide a use case? We didn't thought it would be used because the only callback needed was pressing the "getting started" button.
The index changed event is currently handled only internally.

**Comment by bartvde** [comment]
Use case: I have a carousel of geospatial features, for instance bakeries in Paris. The corresponding map needs to zoom to the location of the bakery.

**Comment by saschb2b** [comment]
I would recommend using just separate slides. You could provide your mapComponent as media and just change a zoom prop is the next slide. So every slide a separate component. To make this more beautiful you could animate your zoom. 

Could look like this.

`<AutoRotatingCarousel
        label="Got to map"
        open
      >
        <Slide
          media={<mapComponent />}
          mediaBackgroundStyle={{ backgroundColor: red400 }}
          contentStyle={{ backgroundColor: red600 }}
          title="This map is normal"
          subtitle="Just a normal map"
        />
        <Slide
          media={<mapComponent zoom={5} animateZoom />}
          mediaBackgroundStyle={{ backgroundColor: blue400 }}
          contentStyle={{ backgroundColor: blue600 }}
          title="This map is zoomed"
          subtitle="Now it's all bigger in slide 2"
        />
      </AutoRotatingCarousel>
`

**Comment by leMaik** [comment]
@saschb2b Animating the zoom won't work because (due to virtualization) the slides are mounted before they are shown. A `onSlideChanged` callback would be a good addition. :+1:

**Comment by saschb2b** [comment]
Good point. Then we'll add that :)

**Comment by bartvde** [comment]
Another question, I see this component is mostly meant to be "modal", would it be easy for me to change / override the styles so that it's not modal? For reference, this is what I'm trying to replace (uses react-slick):

![screen shot 2016-11-03 at 12 56 42](https://cloud.githubusercontent.com/assets/319678/19964971/fe7ac784-a1c4-11e6-9df1-7e54d3f92e56.png)

**Comment by leMaik** [comment]
@bartvde Er... We think that each of our components should do about _one_ thing, and do it well. This component is a Material Design carousel.

Your use case looks like a new project/component on its own. :wink: I don't really see a good reason to bend this component so that it meets your needs, but feel free to take a look on our code to see how you can implement the map popup.

**Comment by bartvde** [comment]
Understood, thanks for the feedback
