### ISSUE TITLE
material-ui deprecation of 'raised' variant

### ISSUE THREAD

**Issue by sys-dev** [TeamWertarbyte/material-auto-rotating-carousel#46]
I'm getting this warning using material-ui 3.5.1

index.js:1452 Warning: Failed prop type: The `raised` variant will be removed in the next major release. `contained` is equivalent and should be used instead.
    in Button (created by WithStyles(Button))
    in WithStyles(Button) (created by AutoRotatingCarousel)
    in div (created by AutoRotatingCarousel)
    in div (created by AutoRotatingCarousel)
    in div (created by AutoRotatingCarousel)
    in Transition (created by Fade)
    in Fade (created by WithTheme(Fade))
    in WithTheme(Fade) (created by AutoRotatingCarousel)
    in RootRef (created by Modal)
    in div (created by Modal)
    in Portal (created by Modal)
    in Modal (created by WithStyles(Modal))
    in WithStyles(Modal) (created by AutoRotatingCarousel)
    in AutoRotatingCarousel (created by WithStyles(AutoRotatingCarousel))
    in WithStyles(AutoRotatingCarousel) (at Welcome.js:153)

**Comment by leMaik** [comment]
I really don't get why Material-UI keeps renaming things lately. :confused: I'll "fix" this soon, but you can ignore this message for now.

**Comment by skirunman** [comment]
@leMaik Material-UI has renamed this prop because name was changed in official Material Design specs by Google. Anyway,  a similar warning is also being generated because Fab button is now a separate component. https://github.com/mui-org/material-ui/pull/13573

**Comment by leMaik** [comment]
@skirunman Renaming this _now_ in material-ui-auto-rotating-carousel would be a breaking change that would prevent it from working with material-ui 1.0.0-3.4.x. That's why I'd like to wait for material-ui 4.0 to be released before changing it and then release a new major version of the carousel.

**Comment by leMaik** [comment]
@sys-dev @skirunman There you go: https://github.com/TeamWertarbyte/material-auto-rotating-carousel/releases/tag/v3.0.0
