### ISSUE TITLE
Incorrect order of slides - Mobile

### ISSUE THREAD

**Issue by matiszz** [TeamWertarbyte/material-auto-rotating-carousel#48]
I have 5 slides. On desktop works good, but in mobile I've found two bugs (only when autoplay=false):

1. The dots doesn't move (only the first dot is lighted)
![image](https://user-images.githubusercontent.com/9436778/50551764-75062a00-0c86-11e9-890f-c81551859dec.png)

2. The slides are disordered. It renders like: **Slide 3, Slide 4, Slide 5, Slide 1, Slide 2, Slide 3** (but the first to render is the number 1)

Did you have the same problem?
Thanks in advance

**Comment by leMaik** [comment]
Hi @matiszz! :wave: I was able to reproduce the issue and it should be fixed in v3.0.1. Please let me know if it still doesn't work for you.
