### ISSUE TITLE
autoplay false setting on the AutoRotatingCarousel is not working

### ISSUE THREAD

**Issue by vchouhan** [TeamWertarbyte/material-auto-rotating-carousel#49]
Tried to use the carousel with autoplay=false but it doesn't seem to work.
I've setup a small demo on this URL.
`https://codesandbox.io/s/xrv093486o`

<img width="714" alt="screen shot 2019-01-21 at 8 04 12 pm" src="https://user-images.githubusercontent.com/1222739/51505976-c3a37180-1db7-11e9-9e8c-26d50176d6af.png">

**Comment by leMaik** [comment]
:+1: for reporting this and for the demo! :clap:

**Comment by leMaik** [comment]
The prop type of `autoplay` is boolean. It should be `autoplay={false}`, then it will work.
