### ISSUE TITLE
Add more buttons

### ISSUE THREAD

**Issue by max10rogerio** [TeamWertarbyte/material-auto-rotating-carousel#50]
hi, i need add more buttons on bottom, where display an button default.

![teste](https://user-images.githubusercontent.com/21085292/56917607-4d876880-6a92-11e9-8177-8e8d9b970310.png)

**Comment by leMaik** [comment]
I think the most flexible way to do this is to allow overriding [the button container](https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/master/src/AutoRotatingCarousel.js#L217) (e.g. to provide a custom `div` container with multiple buttons).
@max10rogerio Do you want to give it a try and submit a PR?

**Comment by saschb2b** [comment]
I close this for now. PR is still welcome though :)
