### ISSUE TITLE
Fast forwarding when switching back to browser tab

### ISSUE THREAD

**Issue by dbdashij** [TeamWertarbyte/material-auto-rotating-carousel#51]
browser: chrome 74.0.3729.131

symptom and steps to reproduce:

1. open a page in a tab with `autoplay` rotating carousel (use default `interval` - 3000 ms)
2. switch to a different tab and take a break for about 10 seconds
3. switch back to the tab in step 1, you will see slides fast forwarding and eventually it slows down to the correct interval

what's expected:

slides in the autoplay carousel rotates exactly every `interval` milliseconds in call cases.

**Comment by leMaik** [comment]
@dbdashij Thanks for the detailed bug report! I was able to reproduce it and reported it upstream at react-swipeable-views. Let's see what causes this issue.

**Comment by leMaik** [comment]
@dbdashij Waiting for my upstream fix to get merged and released. :hourglass_flowing_sand:

**Comment by leMaik** [comment]
@dbdashij Allright, I updated the peer dependency and will release a new version soon. In the meantime, you can update react-swipeable-views to ^0.13.3 to fix this issue.

**Comment by dbdashij** [comment]
Thank you!

**Comment by leMaik** [comment]
> will release a new version soon

Well, it's been a while, but I just published it. :see_no_evil:
