### ISSUE TITLE
Show more than one and horizontally scrollable

### ISSUE THREAD

**Issue by binarykitchen** [TeamWertarbyte/material-auto-rotating-carousel#52]
A horizontally scrollable carousel would be nice. Showing more than one tile at the same time. And still can navigate left and right.

**Comment by binarykitchen** [comment]
Similar like https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html

**Comment by leMaik** [comment]
Great idea for a new project. :+1: We would like to keep this one simple, though; It's just the auto-rotating carousel as seen in the MD guidelines, nothing more, nothing less.

**Comment by binarykitchen** [comment]
Respect that
