### ISSUE TITLE
Is there a way to embed the carousel into the page?

### ISSUE THREAD

**Issue by alexanderwhatley** [TeamWertarbyte/material-auto-rotating-carousel#6]
Is there a way to embed the carousel into the page itself? Right now, when I display it, the carousel takes up the center part of the page, and the gray area surrounding it blocks the rest of the webpage. I have tried adding CSS and style to the div element surrounding it such as:

```
			<div style = {{width: '50%', height: '50%'}}>
				<AutoRotatingCarousel
					label="Get started"
					open
				>
					<Slide
						media={<img src="http://www.icons101.com/icon_png/size_256/id_79394/youtube.png" />}
						mediaBackgroundStyle={{ backgroundColor: red400 }}
						contentStyle={{ backgroundColor: red600 }}
						title="This is a very cool feature"
						subtitle="Just using this will blow your mind."
					/>
					<Slide
						media={<img src="http://www.icons101.com/icon_png/size_256/id_80975/GoogleInbox.png" />}
						mediaBackgroundStyle={{ backgroundColor: blue400 }}
						contentStyle={{ backgroundColor: blue600 }}
						title="Ever wanted to be popular?"
						subtitle="Well just mix two colors and your are good to go!"
					/>
					<Slide
						media={<img src="http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png" />}
						mediaBackgroundStyle={{ backgroundColor: green400 }}
						contentStyle={{ backgroundColor: green600 }}
						title="May the force be with you"
						subtitle="The Force is a metaphysical and ubiquitous power in the Star Wars universe."
					/>
				</AutoRotatingCarousel>
			</div>
```
However, this does not change anything. Thanks for your help.

**Comment by leMaik** [comment]
> Right now, when I display it, the carousel takes up the center part of the page, and the gray area surrounding it blocks the rest of the webpage.

Well, that's exactly what we (and the Material Design Specs) intend this component to be used for. This is not a generic slider for React.

You could try to embed the component by setting `mobile` to `true` and then adding some styles, like this:

```jsx
<AutoRotatingCarousel
  mobile={true}
  style={{ position: 'inherit', width: '50%', height: '50%' }}
>
  // your slides
</AutoRotatingCarousel>
```

**Comment by leMaik** [comment]
@alexanderwhatley That looks like a lot of hacky things. I really think that it would be faster to code your own carousel (feel free to take a look at our code, it's not _that_ hard :wink:) than to hack our component  to fit your very different requirements.

**Comment by saschb2b** [comment]
I'll close this issue for now due to one month of silence. Feel free to open another issue if you have further problems.
