### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by LucaHermann** [TeamWertarbyte/material-auto-rotating-carousel#63]
Hello ! I try to implement a carousel inside a mui project but your are broken so i open this ticket for you !

**node_modules/material-auto-rotating-carousel/lib/AutoRotatingCarousel.js:315**

```
  312 |   enter: _transitions.duration.enteringScreen,
  313 |   exit: _transitions.duration.leavingScreen
  314 | };
> 315 | var hasMultipleChildren = children.length != null;
      | ^  316 | 
  317 | var carousel = _react2.default.createElement(_SwipableCarouselView2.default, {
  318 |   autoplay: open && autoplay && hasMultipleChildren,

```
that the error message throw by react when i try to implement your component.

**Comment by leMaik** [comment]
Would you please not open 8 spam issues the next time you report a problem?

**Comment by saschb2b** [comment]
I closed the other error tickets. Can you provide the implementation? Otherwise it'S hard to pinpoint where your problem is

**Comment by leMaik** [comment]
Looks like you didn't provide any children. Please take a look at the examples provided here: https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/master/src/AutoRotatingCarousel.md
