### ISSUE TITLE
How to override unnecessary styling

### ISSUE THREAD

**Issue by aniruddhashevle** [TeamWertarbyte/material-auto-rotating-carousel#64]
**Why the title and subtitle are necessary in the first place?** **If I don't pass'em as props, still the unnecessary gap is there.** Can not select the classes to remove that unnecessary gap, as the class names are created dynamically.

**If we added className as a prop to the Slide component, actual class (which is gonna generate dynamically) is not added, only className coming from the prop is shown**, hence the styling difference is there than the original one!

**How to remove the unnecessary gap between the image and the bullets of carousel?**
Always better to add styling using classes though!

with title and subtitle:
<img width="997" alt="Screenshot 2019-07-09 at 8 44 31 PM" src="https://user-images.githubusercontent.com/20954198/60888985-91fd6480-a28a-11e9-9990-0cc585ba587a.png">

w/o title and subtitle:
<img width="980" alt="Screenshot 2019-07-09 at 8 44 57 PM" src="https://user-images.githubusercontent.com/20954198/60889019-a5a8cb00-a28a-11e9-92c0-2d51e3fc06c7.png">

**Comment by aniruddhashevle** [comment]
In the styling, on class names, Slide-root-x > Slide-mediaBackground-y (x and y are some random number generated), some height is given as,
`height: calc(100% - 216px);`

If we do,
`height: 100%;`
It works fine.

But how to select the class Slide-mediaBackground-y , as y is dynamically generated?

**Comment by saschb2b** [comment]
Because this component is **not** a image slideshow. It's a specific implementation of the material design spec guidelines. Every slide has text and those styles. If you need it to fit your styling I would suggest using this as inspiration and build your own with react swipeable views. We won't support complete custom styling to fit everyones use cases sorry

**Comment by aniruddhashevle** [comment]
@saschb2b : Thank you for the clarifications and suggestions.
