### ISSUE TITLE
how to start in a given index (ex: resume tutorial)

### ISSUE THREAD

**Issue by ziedHamdi** [TeamWertarbyte/material-auto-rotating-carousel#65]
Hi,

I'm new to js, I would like to open the caroussel in a selected slideIndex. Looking to the code, it seams quite complex (probably to be compatible with older syntax???) for ex:

```
var AutoRotatingCarousel = function (_Component) {
  _inherits(AutoRotatingCarousel, _Component);
...}(_react.Component);
```
instead of 
`class AutoRotatingCarousel extends React.Component {}` ???

Anyway, my problem is elsewhere : I'd like to pass **slideIndex** as a property and it seams I have to fork the project to be able to do it. Am I right? or is there a way I wasn't able to read from the code?

Thanks for the great library, I really appreciate it
Best regards

**Comment by saschb2b** [comment]
We appreciate you using it :)

I think you've looked into the compiled code. Not in the srouce code. See here https://github.com/TeamWertarbyte/material-auto-rotating-carousel/blob/master/src/AutoRotatingCarousel.js
It's a normal react component back when hooks didn't exist.

The component is an uncontrolled one. (more like a black box) The intend was to use it as it is as the material specs suggested. If you are new to react I would also recommend reading controlled vs uncontrolled. 
https://reactjs.org/docs/uncontrolled-components.html
You can achieve making a component handle both but that that's generally harder then decide on one.

What is your use case to controll the index? If you just want to have a controlled slideshow I would suggest using the underlying swipeable views package and build your own.
https://react-swipeable-views.com/

**Comment by ziedHamdi** [comment]
Ok you're right, I was looking at the compiled code

thanks for redirecting me to those useful links. 

Best regards
