### ISSUE TITLE
How do you add a callToAction to the label(button) or is there a way to remove the button?

### ISSUE THREAD

**Issue by adeelibr** [TeamWertarbyte/material-auto-rotating-carousel#7]
HI,
I have experimented in different ways, but couldn't find any solutions, Is there a way to add a call to action to the button or simply remove it? 

Thankyou

**Comment by leMaik** [comment]
Hi, 
there is no way to hide the button, yet. Good idea, we'll add that! 👍 
What do you mean with "call to action"? Do you want to change the button?

**Comment by adeelibr** [comment]
Hi,
What I mean was there should be a trigger to some function when you click the button, I mean that's the whole point of a button, right?

**Comment by saschb2b** [comment]
@adeelibr That's what the prop onStart is for

**Comment by leMaik** [comment]
Exactly, that's what a button should be used for. 😅 You can use the `onStart` property to specify a function that is called when the button is clicked. 

> Fired when the user clicks the getting started button.

**Comment by adeelibr** [comment]
@saschb2b  @leMaik  Oh okay, sorry my bad! Thank you. Can you kindly tell me a hack for now to remove the button.

**Comment by saschb2b** [comment]
The purpose of this component is that the user sees the benefits of your web app. And then close it with a specific action. If you remove the button, there is not not a specific way to dismiss this component at all. By the way, there is no hack to remove it. It is not intended to be removed.

**Comment by adeelibr** [comment]
Oh okay, thankyou for the help.

**Comment by saschb2b** [comment]
But could you elaborate on why you would want to remove the button? In which usecase is that needed? We are trying to improve this component as much as we can.

**Comment by adeelibr** [comment]
I am using this component as slider on my app rather than a modal carousal, I don't need a button on those banners. The slides just keep on rotating there so I don't need a button I just need a rotating slides with some text on it & this component seemed like a perfect solution it is very elegantly made.

**Comment by saschb2b** [comment]
Ah ok. You are using it as an internal information carousel. See #6 as there is someone else wanting to achieve this. This component is really not made for this. We made it like google material intendet it to be. We build this on top of the react-swipeable-views package. Maybe you could build your own slides with it.

**Comment by saschb2b** [comment]
@adeelibr Did you find a solution for your use case?

**Comment by adeelibr** [comment]
Hi,
I ended up using the button for a signup page, so when someone clicks on the button they are taken to the  "Create An Account" page on my site. :)

**Comment by saschb2b** [comment]
Oh ok good idea. Then I close this. You're welcome if you have further ideas :)

**Comment by Guneetgstar** [comment]
> This component is really not made for this. We made it like google material intendet it to be. 

The idea to make it follow `material-design` specs should be allowed to use it anywhere. All that you must have done is to make it a bit modularized so that at least the `material-design` behavior could be extended/exported easily.
If it is possible then can please you tell me how I can abstract this behavior and use it my own costom components?

**Comment by Guneetgstar** [comment]
The extracted [Dots](https://github.com/TeamWertarbyte/material-ui-dots) has done the trick for me. Now I have imported `Dots` and [react-swipeable-views](https://github.com/oliviertassinari/react-swipeable-views) and trying to mimic a similar behavior to `material-auto-rotating-carousel` but for **internal information carousel**.
