### ISSUE TITLE
material-ui-dots@2.0.0 requires a peer of @material-ui/core@^1.0.0

### ISSUE THREAD

**Issue by UndarkAido** [TeamWertarbyte/material-auto-rotating-carousel#72]
Every time I run an NPM action I get the warning
```
npm WARN material-ui-dots@2.0.0 requires a peer of @material-ui/core@^1.0.0 but none is installed. You must install peer dependencies yourself.
```
But this package calls for `"@material-ui/core": "^4.3.2"`. Is there any way to resolve this?

**Comment by leMaik** [comment]
Does everything work for you? That would mean that I'd just have to bump the peer dependency of [material-ui-dots](https://github.com/TeamWertarbyte/material-ui-dots). PR welcome, looks like a low hangig fruit :sunglasses:
