### ISSUE TITLE
hide the lower half in Slide: material-auto-rotating-carousel

### ISSUE THREAD

**Issue by RaedShihab** [TeamWertarbyte/material-auto-rotating-carousel#75]
Is there any way to hide the lower half of the slide (the part down to image)
 ```
<Slide
      media={<img src='http://www.icons101.com/icon_png/size_256/id_76704/Google_Settings.png'/>}
      title='5 May the force be with you'
      subtitle='The Force is a metaphysical and ubiquitous power in the Star Wars fictional universe.'
    />
```
here I tried to comment 'title' and 'subtitle' but that doesn't work as I want

**Comment by justynspooner** [comment]
It doesn't look like that is supported. You could set the height yourself manually.

`mediaBackgroundStyle={{height: "100%",backgroundColor: blue[400] }}`

```
<Slide
          media={
            <img style={{maxWidth:"100%", maxHeight:"100%"}} src="https://www.unawe.org/static/archives/images/screen/heic1406a.jpg" />
          }
          mediaBackgroundStyle={{height: "100%",backgroundColor: blue[400] }}
          style={{ backgroundColor: blue[600] }}
          title=""
          subtitle=""
/>
```

**Comment by leMaik** [comment]
Indeed, this isn't supported. This component is pretty much hard-coded to look like the images in the (old) Material Design specs. If you want to convert it into a slideshow component, feel free to create a fork.
