### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by sstubbs** [TeamWertarbyte/material-auto-rotating-carousel#9]
when I change the direction to rtl it breaks this carousel. Would you be able to fix this?

**Comment by leMaik** [comment]
Thank you for the report, it looks like there is some strange positioning issue if the direction is set to rtl. Mobile landscape mode works fine, though.

**Comment by sstubbs** [comment]
It looks like it also happens in react-swipeable-views and I have created an issue there too. https://github.com/oliviertassinari/react-swipeable-views/issues/243 I would like to help too as I desperately need this feature but am not really sure where to start.

**Comment by leMaik** [comment]
@sstubbs Okay, this means that this should be fixed in react-swipeable-views first, then I can update the version and it will just work.

**Comment by leMaik** [comment]
I'm closing this as it's already possible: https://github.com/oliviertassinari/react-swipeable-views/issues/243#issuecomment-280338432
