### ISSUE TITLE
Option for no modal?

### ISSUE THREAD

**Issue by ahan8927** [TeamWertarbyte/material-auto-rotating-carousel#93]
Is there an option to use this carousel without it being a modal?

**Comment by saschb2b** [comment]
Currently not, as its intended use is as a modal. But you can use the underlying component managing the swipe views.
See https://github.com/oliviertassinari/react-swipeable-views
If you also want those sweet dots you can use https://github.com/TeamWertarbyte/material-ui-dots
With this you can build your own embedded swipeable views as you see fit.

**Comment by Florian-crg** [comment]
Closed ? :/ It is a good idea though
