### ISSUE TITLE
warning message in console : componentWillMount has been renamed

### ISSUE THREAD

**Issue by Eric-Juquel** [TeamWertarbyte/material-auto-rotating-carousel#95]
Hello, 
i Got this warning when opening my carousel :

_Warning: componentWillMount has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: BindKeyboard, Virtualize_

any mistake from my use of this library ?

**Comment by leMaik** [comment]
Neither `BindKeyboard` nor `Virtualized_` are from us, they are both from react-swipeable-views. It seems to have been fixed already (see https://github.com/oliviertassinari/react-swipeable-views/pull/616) but there was no new release since then.

Anyway, you can just ignore it for now (until updating to React 18.x one day). We can't fix this.

**Comment by Eric-Juquel** [comment]
Ok thanks a lot , was a quick response 👍

**Comment by leMaik** [comment]
Sorry, I just noticed that the fix is in fact released in react-swipeable-views 0.14.0-alpha.0 :raised_hands:

So… If you would like to fix this, update the dependency, see if everything works and also bump our peer dependency of React to `^16.8.0`. PR welcome :slightly_smiling_face:

**Comment by Eric-Juquel** [comment]
upgrade switch off the warning , thanks again .
